### ISSUE TITLE
After marking a problem as "done" we can't uncheck that problem

### ISSUE THREAD

**Issue by peddiashrith** [sounishnath003/450-DSA-Tracker#1]
This is helpful if somebody accidentally ticks a checkbox and we can undo it.

**Comment by sounishnath003** [comment]
Yes, I thought One should only click check when he/she fully solved, but what you mentioned that UseCase I didn't cover. 
I welcome you to contribute and make a fix and new Features!!.

**Comment by vaibhavmehra9** [comment]
Fixed raised a PR

**Comment by sounishnath003** [comment]
you did a great job! That's really good work @vaibhavmehra9 , I am now thinking if also questions solutions also people can upload. Because then it will be everything in one place!!

**Comment by vaibhavmehra9** [comment]
Yes it will be a great feature to addon. Or we can add multiple hints below
a problem and can be shown in a popup.

**Comment by sounishnath003** [comment]
I also made 1 new features!

1. Updates where you left off
2. Yours check uncheck options

**Comment by sounishnath003** [comment]
@vaibhavmehra9 
Hey buddy!!
This an Issue with **check/uncheck Questions**, when the user doesn't have any questions completed - while adding it to checklist he reducer (`./src/Reducer/reducer.ts /`) doing - 2 state updation mean - 
1. **first it updates the question to complete**
2.  **At the same time uncheck it**.

Don't know why it's showing this **BUG**

**Comment by vaibhavmehra9** [comment]
@sounishnath003 why this is reopened? This issue has been fixed in my branch

**Comment by sounishnath003** [comment]
I messed in my branch!!, I got you! thanks!
