### ISSUE TITLE
add a "Dark Mode" button

### ISSUE THREAD

**Issue by abhishekpatel946** [sounishnath003/450-DSA-Tracker#12]
### add a "Dark Mode" button

I'm using DSA Preparation 450 but if turn on my `Dark Reader` extension to use for dark mode, then UI got black background and links are not clear. Basically, UI/UX was giving us a badly rendered.

![image](https://user-images.githubusercontent.com/46045014/103439865-bad79d80-4c66-11eb-9e17-95f31280a2a7.png)

**Comment by sounishnath003** [comment]
Hello!! @abhishekpatel946 

That's a very good observation. Currently, at this time dark mode is not supported yet But will be working on it in a week. 
Thanks, a buddy for mentioning...

Do you also want to contribute, then I will add assign you!! @abhishekpatel946

**Comment by sounishnath003** [comment]
Dark Mode is now officially supported by System Default! @abhishekpatel946
