### ISSUE TITLE
Add original owner link in the about page 

### ISSUE THREAD

**Issue by kakashi777** [sounishnath003/450-DSA-Tracker#15]
Please add the original project owner link from where this was copied.

Thank you

**Comment by sounishnath003** [comment]
Issue is FIXED on - [#f96da23](https://github.com/sounishnath003/450-DSA-Tracker/commit/3be5399040f2dec93fd0d44b7a03382cc7213f67).

PS: Now let's contribute more, let's add a feat to save solution code
