### ISSUE TITLE
change color of topic tiles, remaining quesitons and other details are not clearly visible.

### ISSUE THREAD

**Issue by prabhat04011998** [sounishnath003/450-DSA-Tracker#19]
Font is not visible, like completion and left questions.

![image](https://user-images.githubusercontent.com/28345582/108846264-65839100-7604-11eb-89d5-fd234a16a583.png)

**Comment by sounishnath003** [comment]
I often failed to choose colour theme for Dark Mode. It will be better to have you and contribute to improve the screen and user experience!

if you want to contribute raise a PR! Looking forward to have you

**Comment by sounishnath003** [comment]
Would you want to give me an update regarding the matter?

**Comment by prabhat04011998** [comment]
okay i can look into this,but if you allow can I do it on weekends?
