### ISSUE TITLE
No uploading solution option available in certain graph problems

### ISSUE THREAD

**Issue by HarshitShukla25** [sounishnath003/450-DSA-Tracker#26]
- Q,27 Count SCC
- Q. 39 (Seven bridges)
On clicking the upload solution button, blank page appears with no option to upload/edit code

**Comment by HarshitShukla25** [comment]
Word break problem of trie as well

**Comment by sounishnath003** [comment]
## 🎉 [UPDATE]: Issue Solved ~ Navigation Links Formatting Error
![image](https://user-images.githubusercontent.com/40270033/112950063-81c0a380-9157-11eb-96a6-56944442cbcc.png)

<br />

![image](https://user-images.githubusercontent.com/40270033/112950195-a61c8000-9157-11eb-8864-07fdaf27c701.png)


### 💖⭐ Thank You very much for informing this Issue, Hope now everything goes well! Will benefit others as well.
