### ISSUE TITLE
Code Editor Issue

### ISSUE THREAD

**Issue by milanjethwa** [sounishnath003/450-DSA-Tracker#28]
While typing text in code editor, the text are printed in reverse string on code editor.

Here is one test case I tried to type **Hello World** and it was printed **dlroWolleH**
![Code_Editor](https://user-images.githubusercontent.com/12070407/113400182-095c1b80-93bf-11eb-8448-b79dacba3ba2.PNG)

**Comment by sounishnath003** [comment]
A warm thank you, for raising up the issue. I Will FIX it in near time. Actually, at the initial stage, I thought the user will only copy and paste the code, but as you wished to write it just from there, a strange issue is coming up on the way.

Till then try to copy and paste the code - this will do your job! and if you want to FIX always welcome at any time.
