### ISSUE TITLE
Domain Not Opening  https://450-dsa-tracker.netlify.app/

### ISSUE THREAD

**Issue by amit9412** [sounishnath003/450-DSA-Tracker#29]
Please Fix that URL https://450-dsa-tracker.netlify.app/ That is not opening 
Thank you

**Comment by sounishnath003** [comment]
Sorry and frankly speaking I don’t think so. The domain is active and working fine no issues on production as of now!

it might be due to any unknown issue that you’ve faced! I will close the issue
