### ISSUE TITLE
Not able to run it on local machine

### ISSUE THREAD

**Issue by yogi2103** [sounishnath003/450-DSA-Tracker#32]
I forked your repo and tried to set a local run environment but it's giving me an error. Hope you'll tell how to overcome it?
I'm also attaching an image for your refernce.
![Screenshot (185)](https://user-images.githubusercontent.com/57219370/122641213-71e6a900-d121-11eb-8542-e10db5a7b0ae.png)

**Comment by sounishnath003** [comment]
Seems you have not `yarn install` after cloning the repo!. I check with few others they are able to run the project just after cloning! 

Please try to do it again after `yarn install` / `npm install`.

**Comment by yogi2103** [comment]
Yes I tried it after running npm install command. You can even see in the image there's node modules folder which got there after I ran npm install @sounishnath003

**Comment by sounishnath003** [comment]
Try to use with Docker then!. I also not able to understand that the problem with your machine

**Comment by yogi2103** [comment]
I'm not much aware of Docker. Could you please share with me how to use or some quick guide?
