### ISSUE TITLE
GETTING net::ERR_FAILED | Infinite Redirects While Login / Signup

### ISSUE THREAD

**Issue by 5h0bh4nk** [sounishnath003/450-DSA-Tracker#40]
![image](https://user-images.githubusercontent.com/62099471/124393414-0bb07780-dd18-11eb-9e7c-d25e686a784d.png)

POST req not workin in google chrome browser , supposedly due to CORS policy

**Comment by sounishnath003** [comment]
![image](https://user-images.githubusercontent.com/40270033/124394444-1c172100-dd1d-11eb-9ae2-8db9543e6fe2.png)

Seriously? But I tested 5 - 6 times, no server errors / CORS!

**Comment by av1shek** [comment]
> ![image](https://user-images.githubusercontent.com/62099471/124393414-0bb07780-dd18-11eb-9e7c-d25e686a784d.png)
> 
> POST req not workin in google chrome browser , supposedly due to CORS policy

I am also getting same error

**Comment by 5h0bh4nk** [comment]
> ![image](https://user-images.githubusercontent.com/40270033/124394444-1c172100-dd1d-11eb-9ae2-8db9543e6fe2.png)
> 
> Seriously? But I tested 5 - 6 times, no server errors / CORS!

yess . it still persists

**Comment by sounishnath003** [comment]
Test Now! I explicitly allowed headers! required!. Otherwise, need to Test everything!

**Comment by 5h0bh4nk** [comment]
> Test Now! I explicitly allowed headers! required!. Otherwise, need to Test everything!

its still persistent .
have u added 'https://450-dsa-tracker.netlify.app/' to the whitelist for cors??

**Comment by sounishnath003** [comment]
> > Test Now! I explicitly allowed headers! required!. Otherwise, need to Test everything!
> 
> its still persistent .
> have u added 'https://450-dsa-tracker.netlify.app/' to the whitelist for cors??

Yes! @5h0bh4nk .. 

I noticed some mobile / PC users are facing the issues. I guess It's related to cookies. actually, I saw cookies coming from the Backend are not setting up in the browsers. That's why infinite redirects issues and sometimes CORS issues.

**Comment by ykumargupta** [comment]
The same error is facing by me, Please check. Maybe due to earlier data or cookies saved is causing the error. Working fine on mobile. My code data is there which I was relying on . Please fix.

**Comment by sounishnath003** [comment]
*Try Clearing Cookies*
*Allow Cookies in Browser*
*The Login*

**Comment by ykumargupta** [comment]
@sounishnath003  Clearing cookies will remove the database of code progress plus the stored solutions on those questions. Can you please revert back to the previous release?

**Comment by sounishnath003** [comment]
### UPDATE:
I hope the issue has been fixed now!! This was a proxy rewrite error from frontend hosted server!!

Now everything is working as expected!!

**Comment by sounishnath003** [comment]
@ykumargupta 
@5h0bh4nk 
@av1shek 

Guys, Please give feedback !!, I will act accordingly,  It will help me to know better!

**Comment by 5h0bh4nk** [comment]
yup @sounishnath003 
last error fixed but a new one raised

![image](https://user-images.githubusercontent.com/62099471/124499228-4cbd9000-dddb-11eb-8490-1e3314dcf0e6.png)

**Comment by sounishnath003** [comment]
@5h0bh4nk .

Now ?? Please check once

**Comment by 5h0bh4nk** [comment]
cool
its working now

**Comment by sounishnath003** [comment]
Good One! 

Thank you Guys ❤️

**Comment by sounishnath003** [comment]
## ISSUE HAS BEEN FIXED 🎊 🔒 ❤️

**Comment by av1shek** [comment]
> @sounishnath003 Clearing cookies will remove the database of code progress plus the stored solutions on those questions. Can you please revert back to the previous release?

To get back to the previous release, you can host your own website, clone this repo, roll back to the previous commit, and host it again, and hosting on Netlify is very simple.
