### ISSUE TITLE
Index is 0 based

### ISSUE THREAD

**Issue by av1shek** [sounishnath003/450-DSA-Tracker#41]
In the latest update question no starts from 0, which not seems good. It will be better if you can update it with 1 based indexing
![image](https://user-images.githubusercontent.com/59140024/124396496-951b7600-dd27-11eb-9131-f6577b7aa222.png)

**Comment by sounishnath003** [comment]
I put it knowingly if i get similar  requests to change it will do it anyway!

but thanks for your concern
