### ISSUE TITLE
Not able to login/sign up

### ISSUE THREAD

**Issue by pranitha-sridhar** [sounishnath003/450-DSA-Tracker#42]
Have been working on the problems then the site directed me to the login page. But when tried to login or sign up, it was unsuccessful. The button is not responding. 

When I tried the same in another google chrome profile or in Microsoft Edge, it was opening. Would it be resolved, as my code is been saved there?

**Comment by sounishnath003** [comment]
Are you facing - [Issue #40 ](https://github.com/sounishnath003/450-DSA-Tracker/issues/40) ??

**Comment by pranitha-sridhar** [comment]
Yes. Is there any other way to access our data instead of clearing the cookies?

**Comment by sounishnath003** [comment]
@pranitha-sridhar 

### UPDATE:
I hope the issue has been fixed now!! This was a proxy rewrite error from the frontend hosted server!!

Now everything is working as expected!!

**Comment by pranitha-sridhar** [comment]
index.489c568d.js:1 POST https://450-dsa-tracker.netlify.app/proxy/https://dsa-450-backend.herokuapp.com/api/auth/signup 413

Error says: Request Entity Too Large
Won't the progress and solutions be erased while clearing the cookies?

**Comment by sounishnath003** [comment]
Noo

**Comment by sounishnath003** [comment]
Many people replied after clearing all cookies they can now easily login or signup and use the app

**Comment by sounishnath003** [comment]
## ISSUE HAS BEEN FIXED 🎊 🔒 ❤️
