### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by AtluriNikhil** [sounishnath003/450-DSA-Tracker#44]
This is the error I am getting when I am trying to login
And also I am unable to login
![image](https://user-images.githubusercontent.com/63695390/127507173-acbf03d1-4059-4018-8fe5-02f0aee5fa2b.png)

**Comment by sounishnath003** [comment]
## ℹ️  🔔  NOTICE: SERVICE WILL AVAILABLE BY 3rd August 2021 
We are using the Free tier to serve requests, and this month a lot of bills have been generated means I cannot handle them, more than 99 % of resources have been utilized.

Please wait for the date, You'll continue using the app.

**Comment by sounishnath003** [comment]
I cannot afford more at this stage! I understand your situation but please wait for a few days and till then solve in your local and push code to git if fine. 🥲😕


## NOTE: A Sweet Thank you 🙏 
To everyone of you; whoever are using and loving 🥰 the platform, user base grows rapidly this month 😱🤯

you guys broke and utilised more than 98% even (💯) %. It’s a high time to taken care of this measures. Alas I cannot more than this by the time! 😓

**Please be co operative till the time it goes ⬆️**
