### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by 5h0bh4nk** [sounishnath003/450-DSA-Tracker#45]
![image](https://user-images.githubusercontent.com/62099471/127540708-0b154d52-1ded-4d29-970c-44f3126bb463.png)

**Comment by 5h0bh4nk** [comment]
not able to sign in now .

**Comment by sounishnath003** [comment]
#44 Check this Out.

**Comment by sounishnath003** [comment]
## ℹ️  🔔  NOTICE: SERVICE WILL AVAILABLE BY 3rd August 2021 
We are using the Free tier to serve requests, and this month a lot of bills have been generated means I cannot handle them, more than 99 % of resources have been utilized.

Please wait for the date, You'll continue using the app.

**Comment by 5h0bh4nk** [comment]
oh 😐😐😐
thats quite dissapoiting bro
we have our data saved . And needed it

**Comment by sounishnath003** [comment]
I cannot afford more at this stage! I understand your situation but please wait for a few days and till then solve in your local and push code to git if fine. 🥲😕

**Comment by DopeEngineerr** [comment]
Is there any way by which I can export my progress?

**Comment by sounishnath003** [comment]
# SERVICE JS AVAILABLE NOW

**Comment by 5h0bh4nk** [comment]
Thank u @sounishnath003
