### ISSUE TITLE
Cant Login!

### ISSUE THREAD

**Issue by DopeEngineerr** [sounishnath003/450-DSA-Tracker#50]
Is the website down?

**Comment by pranitha-sridhar** [comment]
<img width="386" alt="2021-09-27 (2)" src="https://user-images.githubusercontent.com/58912941/134856057-ed13d0ab-853a-4d9c-9f2c-8f8584397220.png">

The problem keeps occurring every month end. Can something be done about it?

**Comment by sounishnath003** [comment]
## Update
> Please be patient, **Will be back by 2nd October**, no other way I have, A huge user group and active users of around 1.4k, using a daily basis.

**Comment by dipsaili2001** [comment]
@sounishnath003 Brother, why to work directly on main branch?
Do the updates and merge them, later
And from 27-4th October? It's such a long break :C

**Comment by dipsaili2001** [comment]
@sounishnath003 infrastructure means?
