### ISSUE TITLE
Not able to log in after the update.

### ISSUE THREAD

**Issue by GunH-colab** [sounishnath003/450-DSA-Tracker#54]
Hi, my account name had special characters in it. While trying to log in now, it shows "special chars not allowed" or something.

**Comment by sounishnath003** [comment]
Check now!


> Hi, my account name had special characters in it. While trying to log in now, it shows "special chars not allowed" or something.

**Comment by ambideXtrous9** [comment]
Loved the new Interface. But can you place the "reset button" somewhere else....it is so close to continue

**Comment by sounishnath003** [comment]
Thanks

**Comment by GunH-colab** [comment]
> Check now!
> 
> > Hi, my account name had special characters in it. While trying to log in now, it shows "special chars not allowed" or something.

Thanks, its working now!
