### ISSUE TITLE
Refresh issue

### ISSUE THREAD

**Issue by dsouzadyn** [sounishnath003/450-DSA-Tracker#6]
Hi,

Refresh does not seem to work on the hosting platform as expected.

Reproduction steps:
1. Navigate to a topic
2. Refresh

![image](https://user-images.githubusercontent.com/5621469/103266104-f1968500-49d4-11eb-8248-07cd518dc4c2.png)

**Comment by sounishnath003** [comment]
Yes!! Need to integrate HashRouting, useHistory() hooks.!
Do you want to contribute? then that's will be great to see.!!

It will be great if you can contribute to the project and make it to the next level.

**Comment by RohitChattopadhyay** [comment]
Fixed by https://github.com/sounishnath003/450-DSA-Tracker/commit/4428310f1eff7d7f3e9fc83b58ab8a6b88e9fac8
